# config.yaml — your astro-ph bot settings

arxiv:
  categories:
    - "astro-ph.CO"
    - "astro-ph.EP"
    - "astro-ph.GA"
    - "astro-ph.HE"
    - "astro-ph.IM"
    - "astro-ph.SR"
  max_results: 50
  days_back: 1

preferences:
  any_keywords:
    - EHT
    - event horizon telescope
    - Sgr A*
    - M87*
    - MHD
    - GRMHD
    - magnetohydrodynamics
    - EHT
    - black hole
    - event horizon
    - accretion
    - jet
    - radiative transfer
    - VLBI
    - general relativity
    - neutron star
    - pulsar
  all_keywords:
    # e.g. require both terms together"
    - "radiative transfer"
    - "general relativistic magnetohydrodynamics"
  exclude_keywords:
    - education
    - calendar
    - review
    - tutorial
  authors:
    - "Anantua"
    - "Curd"
    - "Gußmann"
    - "Quataert"
  min_score: 1.0

output:
  include_conclusion: true
  email:
    from_addr: "${EMAIL_FROM}"
    to_addrs:
      - "ajd96@proton.me"
      - "ashton.davis3@my.utsa.edu"
    subject_prefix: "[astro-ph digest]"
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    use_starttls: true
    username: "${EMAIL_FROM}"
    password_env: "EMAIL_PASS"
