name: Daily astro-ph Digest

on:
  schedule:
    - cron: "0 13 * * *" # 8am central
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug paths (show what actually exists)
        run: |
          echo "PWD=$(pwd)"
          echo "Repo tree (top level):"
          ls -la
          echo "Full tree (2 levels):"
          find . -maxdepth 2 -type d -print
          echo "Looking for bot.py & requirements.txt:"
          find . -name "bot.py" -o -name "requirements.txt" -maxdepth 3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (wherever requirements.txt actually is)
        run: |
          set -e
          if [ -f "./astroph-bot/requirements.txt" ]; then
            pip install -r ./astroph-bot/requirements.txt
          elif [ -f "./requirements.txt" ]; then
            pip install -r ./requirements.txt
          else
            echo "requirements.txt not found"; exit 1
          fi

      - name: Run astro-ph bot (try subdir, then root)
        env:
          ASTROPH_EMAIL_PASSWORD: ${{ secrets.ASTROPH_EMAIL_PASSWORD }}
        run: |
          set -e
          echo "PWD=$(pwd)"
          if [ -f "./astroph-bot/bot.py" ]; then
            echo "Running ./astroph-bot/bot.py"
            python ./astroph-bot/bot.py
          elif [ -f "./bot.py" ]; then
            echo "Running ./bot.py"
            python ./bot.py
          else
            echo "bot.py not found in repo"; exit 1
          fi
